name: build-linux

on: [workflow_dispatch]

jobs:
  build_wheels:
    env:
      CIBW_BUILD: "cp313-manylinux_x86_64"
      
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.22.0

      - name: Build wheels
        run: python -m cibuildwheel --output-dir=wheelhouse

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheel-${{matrix.os}}-${{strategy.job-index}}
          path: wheelhouse/*whl
